### ISSUE TITLE
electron运行时候出现版本错误，该肿么解决

### ISSUE THREAD

**Issue by AmperZDH** [Charliecheung2/toastfish-mac#1]
输入
1.`npm install --save-dev`
2.`npm run build`
3.`electron .`
就报了下面的版本错
```
App threw an error during load
Error: The module '/Users/amber.d/Desktop/Working/toastfish-mac/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 110. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Users/amber.d/Desktop/Working/toastfish-mac/node_modules/bindings/bindings.js:112:48)
    at new Database (/Users/amber.d/Desktop/Working/toastfish-mac/node_modules/better-sqlite3/lib/database.js:48:64)
```

**Comment by AmperZDH** [comment]
我换了electron node better-sqlite3版本依旧报错

**Comment by Charliecheung2** [comment]
scripts里面加上rebuild 跑个rebuild看看
`
    "rebuild": "electron-rebuild -f -w better-sqlite3",
`
